/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_user_myapplication_AESJni */

#ifndef _Included_com_example_user_myapplication_AESJni
#define _Included_com_example_user_myapplication_AESJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_user_myapplication_AESJni
 * Method:    getKeyValue
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_example_user_myapplication_AESJni_getKeyValue
  (JNIEnv *, jobject);

/*
 * Class:     com_example_user_myapplication_AESJni
 * Method:    getIv
 * Signature: ()[B
 */
JNIEXPORT jbyteArray JNICALL Java_com_example_user_myapplication_AESJni_getIv
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
